import type { Client, Kpi, Order, PreOrder } from "@/types/crm";

export const clients: Client[] = [
  {
    id: "cl-1001",
    name: "Anna Petrova",
    company: "Northwind LLC",
    email: "anna@northwind.io",
    phone: "+1 212 555 0101",
    status: "active",
    totalRevenue: 25600,
  },
  {
    id: "cl-1002",
    name: "Michael Brown",
    company: "Blue Horizon",
    email: "michael@bluehorizon.com",
    phone: "+1 212 555 0102",
    status: "lead",
    totalRevenue: 4200,
  },
  {
    id: "cl-1003",
    name: "Sofia Ivanova",
    company: "Bright Labs",
    email: "sofia@brightlabs.ai",
    phone: "+1 212 555 0103",
    status: "active",
    totalRevenue: 18900,
  },
  {
    id: "cl-1004",
    name: "David Clark",
    company: "Apex Systems",
    email: "david@apexsys.co",
    phone: "+1 212 555 0104",
    status: "inactive",
    totalRevenue: 7600,
  },
  {
    id: "cl-1005",
    name: "Elena Smirnova",
    company: "Orbit Retail",
    email: "elena@orbitretail.com",
    phone: "+1 212 555 0105",
    status: "active",
    totalRevenue: 33400,
  },
];

export const orders: Order[] = [
  {
    id: "ord-5001",
    clientId: "cl-1001",
    clientName: "Anna Petrova",
    title: "Enterprise CRM license",
    amount: 6200,
    status: "paid",
    createdAt: "2026-04-18",
  },
  {
    id: "ord-5002",
    clientId: "cl-1003",
    clientName: "Sofia Ivanova",
    title: "Support package",
    amount: 1800,
    status: "pending",
    createdAt: "2026-04-17",
  },
  {
    id: "ord-5003",
    clientId: "cl-1005",
    clientName: "Elena Smirnova",
    title: "Integration services",
    amount: 4200,
    status: "paid",
    createdAt: "2026-04-15",
  },
  {
    id: "ord-5004",
    clientId: "cl-1002",
    clientName: "Michael Brown",
    title: "Pilot onboarding",
    amount: 1500,
    status: "overdue",
    createdAt: "2026-04-12",
  },
  {
    id: "ord-5005",
    clientId: "cl-1001",
    clientName: "Anna Petrova",
    title: "Additional seats",
    amount: 3200,
    status: "pending",
    createdAt: "2026-04-10",
  },
];

export const dashboardKpis: Kpi[] = [
  { id: "kpi-1", label: "Total revenue", value: "$89,700", trend: "+12.4%" },
  { id: "kpi-2", label: "Active clients", value: "42", trend: "+5.1%" },
  { id: "kpi-3", label: "Open orders", value: "17", trend: "+2.0%" },
  { id: "kpi-4", label: "Conversion rate", value: "31%", trend: "+1.8%" },
];

export const preOrders: PreOrder[] = [
  {
    id: "po-9001",
    orderId: "ord-5001",
    clientPrice: "$42.00",
    clientName: "Anna Petrova",
    requestedAt: "2026-04-20 09:15",
    scheduledFor: "2026-04-21 14:00",
    pointA: "New York, 5th Ave 121",
    pointB: "Newark, Edison Pl 20",
    driverAssigned: true,
    driverId: "drv-201",
    driverFirstName: "John",
    driverLastName: "Miller",
    driverPhone: "+1 917 555 0191",
  },
  {
    id: "po-9002",
    orderId: "ord-5002",
    clientPrice: "$35.00",
    clientName: "Sofia Ivanova",
    requestedAt: "2026-04-20 10:40",
    scheduledFor: "2026-04-22 11:30",
    pointA: "Jersey City, Hudson St 45",
    pointB: "Brooklyn, Flatbush Ave 218",
    driverAssigned: false,
    driverId: null,
    driverFirstName: null,
    driverLastName: null,
    driverPhone: null,
  },
  {
    id: "po-9003",
    orderId: "ord-5004",
    clientPrice: "$29.00",
    clientName: "Michael Brown",
    requestedAt: "2026-04-20 11:05",
    scheduledFor: "2026-04-21 17:20",
    pointA: "Queens, Queens Blvd 980",
    pointB: "Manhattan, Broadway 350",
    driverAssigned: true,
    driverId: "drv-307",
    driverFirstName: "Daniel",
    driverLastName: "Lewis",
    driverPhone: "+1 347 555 0137",
  },
  {
    id: "po-9004",
    orderId: "ord-5003",
    clientPrice: "$51.00",
    clientName: "Elena Smirnova",
    requestedAt: "2026-04-20 12:25",
    scheduledFor: "2026-04-23 08:45",
    pointA: "Bronx, Grand Concourse 700",
    pointB: "Staten Island, Bay St 112",
    driverAssigned: false,
    driverId: null,
    driverFirstName: null,
    driverLastName: null,
    driverPhone: null,
  },
];

export const formatCurrency = (value: number) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
